/* Generated by Yosys 0.24+1 (git sha1 7ad7b550c, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "iiitb_gray_cntr.v:2.1-25.10" *)
module iiitb_gray_cntr(clk, rst, bcd_value, gray_count);
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "iiitb_gray_cntr.v:20.87-20.112" *)
  wire _03_;
  (* src = "iiitb_gray_cntr.v:20.60-20.85" *)
  wire _04_;
  (* src = "iiitb_gray_cntr.v:20.33-20.58" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "iiitb_gray_cntr.v:6.18-6.27" *)
  wire _13_;
  (* src = "iiitb_gray_cntr.v:6.18-6.27" *)
  wire _14_;
  (* src = "iiitb_gray_cntr.v:6.18-6.27" *)
  wire _15_;
  (* src = "iiitb_gray_cntr.v:7.18-7.28" *)
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "iiitb_gray_cntr.v:5.7-5.10" *)
  wire _24_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_gray_cntr.v:19.18-19.31|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _25_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_gray_cntr.v:19.18-19.31|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  (* src = "iiitb_gray_cntr.v:6.18-6.27" *)
  output [3:0] bcd_value;
  wire [3:0] bcd_value;
  (* src = "iiitb_gray_cntr.v:4.7-4.10" *)
  input clk;
  wire clk;
  (* src = "iiitb_gray_cntr.v:7.18-7.28" *)
  output [3:0] gray_count;
  wire [3:0] gray_count;
  (* src = "iiitb_gray_cntr.v:5.7-5.10" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(_14_),
    .B(_24_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _35_ (
    .A(_13_),
    .B(_14_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xor2_1 _36_ (
    .A(_15_),
    .B(_17_),
    .X(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _37_ (
    .A(_24_),
    .B(_18_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(_13_),
    .A2(_14_),
    .B1(_15_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__xor2_1 _39_ (
    .A(_16_),
    .B(_19_),
    .X(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(_24_),
    .B(_20_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand3_1 _41_ (
    .A(_13_),
    .B(_14_),
    .C(_15_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__xor2_1 _42_ (
    .A(_16_),
    .B(_21_),
    .X(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _43_ (
    .A(_24_),
    .B(_22_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _44_ (
    .A(_13_),
    .B(_24_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a21o_1 _45_ (
    .A1(_13_),
    .A2(_14_),
    .B1(_24_),
    .X(_23_)
  );
  sky130_fd_sc_hd__nor2_1 _46_ (
    .A(_17_),
    .B(_23_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3b_1 _47_ (
    .A(_24_),
    .B(_19_),
    .C_N(_21_),
    .Y(_12_)
  );
  (* src = "iiitb_gray_cntr.v:10.1-24.4" *)
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(_27_),
    .Q(gray_count[0])
  );
  (* src = "iiitb_gray_cntr.v:10.1-24.4" *)
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_28_),
    .Q(gray_count[1])
  );
  (* src = "iiitb_gray_cntr.v:10.1-24.4" *)
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_29_),
    .Q(gray_count[2])
  );
  (* src = "iiitb_gray_cntr.v:10.1-24.4" *)
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_30_),
    .Q(gray_count[3])
  );
  (* src = "iiitb_gray_cntr.v:10.1-24.4" *)
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_31_),
    .Q(bcd_value[0])
  );
  (* src = "iiitb_gray_cntr.v:10.1-24.4" *)
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_32_),
    .Q(bcd_value[1])
  );
  (* src = "iiitb_gray_cntr.v:10.1-24.4" *)
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_33_),
    .Q(bcd_value[2])
  );
  assign _25_[3:1] = { gray_count[3], bcd_value[2:1] };
  assign _26_[0] = _25_[0];
  assign bcd_value[3] = gray_count[3];
  assign _13_ = bcd_value[0];
  assign _14_ = bcd_value[1];
  assign _15_ = bcd_value[2];
  assign _16_ = gray_count[3];
  assign _24_ = rst;
  assign _27_ = _06_;
  assign _28_ = _07_;
  assign _29_ = _08_;
  assign _30_ = _09_;
  assign _31_ = _10_;
  assign _32_ = _11_;
  assign _33_ = _12_;
endmodule
